#!/usr/bin/env python
import sys
import glob
import os
import importlib.util

# print(sys.argv)
# scripts = glob.glob(r'scripts/**.py')
# print(scripts)

# spec = importlib.util.spec_from_file_location()
# foo = importlib.util.module_from_spec(spec)
# spec.loader.exec_module(foo)


from importlib.machinery import SourceFileLoader
if(len(sys.argv)):
    scripts = glob.glob(r'scripts/*.py')+glob.glob(r'scripts/*/*.py')
    print("available scripts")
    print(scripts)
    exit()

# imports the module from the given path
module = SourceFileLoader("script", "scripts/"+sys.argv[1]+".py").load_module()